### ISSUE TITLE
Failed to compose DFAs

### ISSUE THREAD

**Issue by tomyaacov** [mvcisback/dfa#4]
Hi,
I started using the package and tried to run the following code described at the README:
```python
parity = DFA(
    start=0, inputs={0, 1}, label=lambda s: s,
    transition=lambda s, c: (s + c) & 1,
)

self_composed = parity | parity

assert self_composed.label([(0, 0), (1, 0)]) == (1, 0)
```
and I'm getting the following error:

`TypeError: unsupported operand type(s) for |: 'DFA' and 'DFA'`

**Comment by mvcisback** [comment]
hi, what version of python and the dfa package are you using?

**Comment by mvcisback** [comment]
Hi @tomyaacov 

Sorry about the confusion. I just realized that there was a regression in the readme. The composition API was dropped a while back and it was removed from the readme.

It looks like it was accidentally brought back when cherry picking and old patch.

**Comment by tomyaacov** [comment]
Ok.. thanks for replying. Is there an older version of the package which includes composition?

**Comment by mvcisback** [comment]
So it was explored in an experimental feature branch.

I actually think it might be good to try and explore adding the feature again, but I won't have time to really investigate (and then commit to maintaining) until ~May.

I'm happy to accept a PR though.

Are you just interested in parallel composition? Or do you generally want parallel + sequential composition?

For small alphabets,  it's fairly easy to write code that implements these. For example parallel composition should be something like:

```
from dfa import DFA

def par_compose(dfas: list[DFA]) -> DFA:
    def transition(state, char):
        return tuple(d._transition(s, c) for d, s, c in zip(dfas, state, char))
        
   def label(state):
       return tuple(d._label(s) for s in zip(dfas, state))
       
   return DFA(
       start=tuple(d.start for d in dfas),
       inputs=product(d.inputs for d in dfas),
       outputs=product(d.outputs for d in dfas),
       label=label,
       transition=transition,
   )
```

**Comment by mvcisback** [comment]
To be clear, the real pain is writing logic to symbolically handle sum and product alphabets.

It's not impossible, but I recall there being subtle edge cases.

Typically, I do composition at the circuit level using the py-aigerlibrary.

**Comment by tomyaacov** [comment]
Will check it out. Thanks!
