### ISSUE TITLE
Incompatibility with dill (and pickle)

### ISSUE THREAD

**Issue by LaufferN** [mvcisback/dfa#7]
`dfa` objects are incompatible with both `pickle` and `dill`.
```
import dfa
import dill

dfa1 = dfa.DFA(start=0,
               inputs = {0,1},
               label=lambda s: (s % 4) == 3,
               transition=lambda s, c: (s + c) % 4,
       )

with open('temp.dill', 'wb') as f:
    dill.dump(dfa1, f)
```

This code fails with error `_pickle.PicklingError: Can't pickle <function _make_lookuper.<locals>.make_lookuper at 0x102a2b5e0>: it's not found as funcy.calc._make_lookuper.<locals>.make_lookuper`.

**Comment by mvcisback** [comment]
Fixed in #8ef56625
